create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 200),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.tasks enable row level security;

drop policy if exists "public can read tasks" on public.tasks;
create policy "public can read tasks"
on public.tasks for select
to anon, authenticated
using (true);

drop policy if exists "public can insert tasks" on public.tasks;
create policy "public can insert tasks"
on public.tasks for insert
to anon, authenticated
with check (true);

drop policy if exists "public can update tasks" on public.tasks;
create policy "public can update tasks"
on public.tasks for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public can delete tasks" on public.tasks;
create policy "public can delete tasks"
on public.tasks for delete
to anon, authenticated
using (true);